-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "dailyCalorieNorm" INTEGER;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "dailyCalorieGoal" INTEGER;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "workouts" TEXT;
